BOOTLOADER = caterina
MCU = atmega32u4

OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
AUDIO_ENABLE = yes
MUSIC_ENABLE = no

DYNAMIC_MACRO_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

#HAPTIC FEEBACK
HAPTIC_ENABLE = no

RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BOOTMAGIC_ENABLE = no
LTO_ENABLE = yes
CAPS_WORD_ENABLE = yes
