CONVERT_TO = helios

OLED_ENABLE = yes
OLED_DRIVER = ssd1306
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes

AUDIO_ENABLE = no
MUSIC_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
HAPTIC_ENABLE = no
RGB_MATRIX_ENABLE = no
CAPS_WORD_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
