BOOTLOADER = caterina
MCU = atmega32u4

ENCODER_ENABLE = no
OLED_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGBLIGHT_ENABLE = no
COMBO_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BOOTMAGIC_ENABLE = yes
LTO_ENABLE = yes
