#pragma once

#define DIODE_DIRECTION COL2ROW
#define MATRIX_ROWS 8
#define MATRIX_COLS 7

#define EE_HANDS
#define USE_SERIAL

// #define SOFT_SERIAL_PIN GP13
// #define SERIAL_PIO_USE_PIO1

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1
#define SERIAL_USART_PIN_SWAP

#define MATRIX_ROW_PINS { GP4, GP5, GP6, GP7 }
#define MATRIX_COL_PINS { GP29, GP28, GP27, GP26, GP22, GP13, GP12 }

#define ENCODERS_PAD_A { GP15 }
#define ENCODERS_PAD_B { GP16 }

#define MATRIX_ROW_PINS_RIGHT { GP29, GP28, GP27, GP26 }
#define MATRIX_COL_PINS_RIGHT { GP4, GP5, GP6, GP7, GP8, NO_PIN, NO_PIN }

#define ENCODERS_PAD_A_RIGHT { }
#define ENCODERS_PAD_B_RIGHT { }

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#define TAPPING_TERM 190
// #define IGNORE_MOD_TAP_INTERRUPT

#ifdef POINTING_DEVICE_ENABLE
  #define CIRQUE_PINNACLE_DIAMETER_MM 40
  #define CIRQUE_PINNACLE_CURVED_OVERLAY

  #define POINTING_DEVICE_TASK_THROTTLE_MS 10
  #define POINTING_DEVICE_RIGHT
  #define SPLIT_POINTING_ENABLE

  #define POINTING_DEVICE_ROTATION_270

  #define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#endif
