#pragma once

#define TAPPING_TERM 190
#define TAPPING_TOGGLE 3
#define IGNORE_MOD_TAP_INTERRUPT

#ifdef OLED_ENABLE
  #define OLED_TIMEOUT 20000
#endif

#ifdef POINTING_DEVICE_ENABLE
  #define CIRQUE_PINNACLE_DIAMETER_MM 40
  #define CIRQUE_PINNACLE_CURVED_OVERLAY

  #define POINTING_DEVICE_TASK_THROTTLE_MS 10
  #define POINTING_DEVICE_RIGHT
  #define SPLIT_POINTING_ENABLE
  #define MASTER_RIGHT


  #define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#endif
