BOOTLOADER = caterina
MCU = atmega32u4

ENCODER_ENABLE = no
OLED_ENABLE = yes
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
LTO_ENABLE = yes
