MCU = RP2040
BOOTLOADER = rp2040

EXTRAKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306

ENCODER_ENABLE = no
BACKLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BOOTMAGIC_ENABLE = no
LTO_ENABLE = no
