#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_WWW_HOME, KC_F17, KC_F18, KC_F15, KC_CALCULATOR, KC_EXECUTE, KC_STOP, KC_WWW_FAVORITES, KC_F14)
};

