MCU = RP2040
BOOTLOADER = rp2040

ENCODER_ENABLE = yes
OLED_ENABLE = no
EXTRAKEY_ENABLE = yes
BACKLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BOOTMAGIC_ENABLE = no
LTO_ENABLE = no
